# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb10ed3ad5139b76b71f8b66b622894553fbed5c72e09898803cca6dbf5a66da210804a3fd0a5a0d1e7687c8ff90c6fea4d7d8e8c6d970b65742f8f650072f72

test:
  secret_key_base: 7ad4a6c6751437c7b0c759cf1b828e4d70b5ce48d244ac83a61d9ca1631a7bc216bdb77f77443d09fc71c615e499c5332a7a8ad3ca739d4b591ab096a2c6251a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
